package com.mlife.web.holder;

import com.mlife.web.holder.Response.ObjectAddReport;
import com.mlife.web.holder.Response.ObjectAddServiceRequest;
import com.mlife.web.holder.Response.ObjectAddTicket;
import com.mlife.web.holder.Response.ObjectAddedValueList;
import com.mlife.web.holder.Response.ObjectAllProperty;
import com.mlife.web.holder.Response.ObjectAppVersion;
import com.mlife.web.holder.Response.ObjectBookClubhouse;
import com.mlife.web.holder.Response.ObjectChangeBookingStatus;
import com.mlife.web.holder.Response.ObjectChangeGroupAbout;
import com.mlife.web.holder.Response.ObjectChangeGroupDetails;
import com.mlife.web.holder.Response.ObjectClubHouseList;
import com.mlife.web.holder.Response.ObjectCommitteeManagmentList;
import com.mlife.web.holder.Response.ObjectDeleteProfileEducationDetails;
import com.mlife.web.holder.Response.ObjectExploreGroups;
import com.mlife.web.holder.Response.ObjectForgotPassword;
import com.mlife.web.holder.Response.ObjectForgotPasswordVerify;
import com.mlife.web.holder.Response.ObjectGetAvailableTimeSlot;
import com.mlife.web.holder.Response.ObjectGetKey;
import com.mlife.web.holder.Response.ObjectGetPostPaymentDetails;
import com.mlife.web.holder.Response.ObjectGetPosts;
import com.mlife.web.holder.Response.ObjectGetProfileDetails;
import com.mlife.web.holder.Response.ObjectGetProjectDetail;
import com.mlife.web.holder.Response.ObjectGetTimeSlot;
import com.mlife.web.holder.Response.ObjectLikePost;
import com.mlife.web.holder.Response.ObjectLoadProfileSettings;
import com.mlife.web.holder.Response.ObjectLoadVASSettings;
import com.mlife.web.holder.Response.ObjectLoginOTPResponse;
import com.mlife.web.holder.Response.ObjectLogout;
import com.mlife.web.holder.Response.ObjectMembersbyGroup;
import com.mlife.web.holder.Response.ObjectNoticeList;
import com.mlife.web.holder.Response.ObjectOfferList;
import com.mlife.web.holder.Response.ObjectProjectConstructionUpdate;
import com.mlife.web.holder.Response.ObjectProjectLocation;
import com.mlife.web.holder.Response.ObjectPropertyDetailsResponse;
import com.mlife.web.holder.Response.ObjectPropertyResponse;
import com.mlife.web.holder.Response.ObjectRemoveGroupMember;
import com.mlife.web.holder.Response.ObjectRemoveOffer;
import com.mlife.web.holder.Response.ObjectSaveVASRequirements;
import com.mlife.web.holder.Response.ObjectSendNewEnquiry;
import com.mlife.web.holder.Response.ObjectSetGroupImage;
import com.mlife.web.holder.Response.ObjectSetProfileImage;
import com.mlife.web.holder.Response.ObjectSetSiteVisitDate;
import com.mlife.web.holder.Response.ObjectTicketLogs;
import com.mlife.web.holder.Response.ObjectUpdateGroupJoinRequest;
import com.mlife.web.holder.Response.ObjectUpdatePost;
import com.mlife.web.holder.Response.ObjectUpdateProfileDetails;
import com.mlife.web.holder.Response.ObjectUpdateProfileEducation;
import com.mlife.web.holder.Response.ObjectViewGroup;
import com.mlife.web.holder.Response.ObjectAcceptEvent;
import com.mlife.web.holder.Response.ObjectAddCallBack;
import com.mlife.web.holder.Response.ObjectAddClassified;
import com.mlife.web.holder.Response.ObjectAddComments;
import com.mlife.web.holder.Response.ObjectAddTicketLog;
import com.mlife.web.holder.Response.ObjectAddUserVas;
import com.mlife.web.holder.Response.ObjectAmentieeList;
import com.mlife.web.holder.Response.ObjectCancelSiteVisit;
import com.mlife.web.holder.Response.ObjectChangeGroupName;
import com.mlife.web.holder.Response.ObjectConstructionUpdatesResponse;
import com.mlife.web.holder.Response.ObjectCreateGroup;
import com.mlife.web.holder.Response.ObjectCreatePost;
import com.mlife.web.holder.Response.ObjectDeletePost;
import com.mlife.web.holder.Response.ObjectEventList;
import com.mlife.web.holder.Response.ObjectGetDownloadDocuments;
import com.mlife.web.holder.Response.ObjectGetPaymentDetails;
import com.mlife.web.holder.Response.ObjectGetProduct;
import com.mlife.web.holder.Response.ObjectGetServiceRequests;
import com.mlife.web.holder.Response.ObjectGroupAboutbyGroup;
import com.mlife.web.holder.Response.ObjectHomeBannerList;
import com.mlife.web.holder.Response.ObjectJoinGroup;
import com.mlife.web.holder.Response.ObjectJoinedGrops;
import com.mlife.web.holder.Response.ObjectLoadComments;
import com.mlife.web.holder.Response.ObjectLoadDocuments;
import com.mlife.web.holder.Response.ObjectLoadGroupTypes;
import com.mlife.web.holder.Response.ObjectLoadSiteVisits;
import com.mlife.web.holder.Response.ObjectLoginResponse;
import com.mlife.web.holder.Response.ObjectMyGroups;
import com.mlife.web.holder.Response.ObjectNotificationList;
import com.mlife.web.holder.Response.ObjectPaymentResponse;

import com.mlife.web.holder.Response.ObjectProjectAmenities;
import com.mlife.web.holder.Response.ObjectProjectGallery;
import com.mlife.web.holder.Response.ObjectProjectList;
import com.mlife.web.holder.Response.ObjectProjectOffers;
import com.mlife.web.holder.Response.ObjectResidentList;
import com.mlife.web.holder.Response.ObjectSubmitFeedback;
import com.mlife.web.holder.Response.ObjectTicketList;
import com.mlife.web.holder.Response.ObjectViewProfileDetails;
import com.mlife.web.holder.Response.ObjectkeyLocation;

public interface DataHolder {

    ObjectLoginResponse objectLoginResponse = new ObjectLoginResponse();
    ObjectLoginOTPResponse oObjectLoginOTPResponse = new ObjectLoginOTPResponse();
    ObjectLoginOTPResponse ooObjectLoginOTPResponse = new ObjectLoginOTPResponse();
    ObjectPropertyResponse objectPropertyResponse = new ObjectPropertyResponse();
    ObjectPropertyDetailsResponse objectPropertyDetailsResponse = new ObjectPropertyDetailsResponse();
    ObjectConstructionUpdatesResponse objectConstructionUpdatesResponse = new ObjectConstructionUpdatesResponse();
    ObjectAllProperty objectAllProperty = new ObjectAllProperty();
    ObjectSetSiteVisitDate objectSetSiteVisitDate = new ObjectSetSiteVisitDate();
    ObjectLoadSiteVisits objectLoadSiteVisits = new ObjectLoadSiteVisits();
    ObjectLoadGroupTypes objectLoadGroupTypes = new ObjectLoadGroupTypes();
    ObjectCreateGroup objectCreateGroup = new ObjectCreateGroup();
    ObjectExploreGroups objectExploreGroups = new ObjectExploreGroups();
    ObjectCancelSiteVisit objectCancelSiteVisit = new ObjectCancelSiteVisit();
    ObjectJoinGroup objectJoinGroup = new ObjectJoinGroup();
    ObjectJoinedGrops objectJoinedGrops = new ObjectJoinedGrops();
    ObjectMyGroups objectMyGroups = new ObjectMyGroups();
    ObjectViewGroup objectViewGroup = new ObjectViewGroup();
    ObjectNoticeList objectNoticeList = new ObjectNoticeList();
    ObjectCreatePost objectCreatePost = new ObjectCreatePost();
    ObjectEventList objectEventList = new ObjectEventList();
    ObjectAcceptEvent objectAcceptEvent = new ObjectAcceptEvent();
    ObjectGetPosts objectGetPosts = new ObjectGetPosts();
    ObjectAddComments objectAddComments = new ObjectAddComments();
    ObjectLoadComments objectLoadComments = new ObjectLoadComments();
    ObjectLikePost objectLikePost = new ObjectLikePost();
    ObjectClubHouseList objectClubHouseList = new ObjectClubHouseList();
    ObjectAmentieeList objectAmentieeList = new ObjectAmentieeList();
    ObjectChangeBookingStatus objectChangeBookingStatus = new ObjectChangeBookingStatus();
    ObjectBookClubhouse objectBookClubhouse = new ObjectBookClubhouse();
    ObjectGetPaymentDetails objectGetPaymentDetails = new ObjectGetPaymentDetails();
    ObjectAddedValueList objectAddedValueListInterior = new ObjectAddedValueList();
    ObjectAddedValueList objectAddedValueListFurniture = new ObjectAddedValueList();
    ObjectLogout objectLogout = new ObjectLogout();
    ObjectAppVersion objectAppVersion = new ObjectAppVersion();
    ObjectForgotPasswordVerify objectForgotPasswordVerify = new ObjectForgotPasswordVerify();
    ObjectPaymentResponse objectPaymentResponse = new ObjectPaymentResponse();

    ObjectOfferList objectOfferListAdmin = new ObjectOfferList();
    ObjectOfferList objectOfferListSell = new ObjectOfferList();
    ObjectOfferList objectOfferListRent = new ObjectOfferList();
    ObjectOfferList objectMyOfferList = new ObjectOfferList();

    ObjectAddClassified objectAddClassified = new ObjectAddClassified();

    ObjectTicketList objectTicketListEnquiries = new ObjectTicketList();
    ObjectTicketList objectTicketListRequest = new ObjectTicketList();
    ObjectTicketList objectTicketListComplaints = new ObjectTicketList();

    ObjectAddCallBack objectAddCallBack = new ObjectAddCallBack();
    ObjectAddTicket objectAddTicket = new ObjectAddTicket();
    ObjectProjectList objectProjectList = new ObjectProjectList();
    ObjectGetProjectDetail objectGetProjectDetail = new ObjectGetProjectDetail();
    ObjectProjectAmenities objectProjectAmenities = new ObjectProjectAmenities();
    ObjectProjectGallery objectProjectGallery = new ObjectProjectGallery();
    ObjectProjectConstructionUpdate objectProjectConstructionUpdate = new ObjectProjectConstructionUpdate();
    ObjectProjectLocation objectProjectLocation = new ObjectProjectLocation();
    ObjectTicketLogs objectTicketLogs = new ObjectTicketLogs();
    ObjectAddTicketLog objectAddTicketLog = new ObjectAddTicketLog();
    ObjectGetPostPaymentDetails objectGetPostPaymentDetails = new ObjectGetPostPaymentDetails();
    ObjectProjectOffers objectProjectOffers = new ObjectProjectOffers();
    ObjectChangeGroupName objectChangeGroupName = new ObjectChangeGroupName();
    ObjectSetGroupImage objectSetGroupImage = new ObjectSetGroupImage();
    ObjectMembersbyGroup objectMembersbyGroup = new ObjectMembersbyGroup();
    ObjectGroupAboutbyGroup objectGroupAboutbyGroup = new ObjectGroupAboutbyGroup();
    ObjectChangeGroupAbout objectChangeGroupAbout = new ObjectChangeGroupAbout();
    ObjectGetServiceRequests objectGetServiceRequests = new ObjectGetServiceRequests();
    ObjectResidentList objectResidentList = new ObjectResidentList();
    ObjectCommitteeManagmentList objectCommitteeManagmentList = new ObjectCommitteeManagmentList();
    ObjectNotificationList objectNotificationList = new ObjectNotificationList();
    ObjectDeletePost objectDeletePost = new ObjectDeletePost();
    ObjectAddReport objectAddReport = new ObjectAddReport();
    ObjectAddServiceRequest objectAddServiceRequest = new ObjectAddServiceRequest();
    ObjectSubmitFeedback objectSubmitFeedback = new ObjectSubmitFeedback();
    ObjectLoadDocuments objectLoadDocuments = new ObjectLoadDocuments();
    ObjectGetDownloadDocuments objectGetDownloadDocuments = new ObjectGetDownloadDocuments();
    ObjectHomeBannerList objectHomeBannerList= new ObjectHomeBannerList();
    ObjectkeyLocation objectKeyLocation = new ObjectkeyLocation();
    ObjectUpdatePost objectUpdatePost = new ObjectUpdatePost();
    ObjectGetProduct objectGetProduct = new ObjectGetProduct();
    ObjectAddUserVas objectAddUserVas = new ObjectAddUserVas();
    ObjectGetTimeSlot objectGetTimeSlot = new ObjectGetTimeSlot();
    ObjectGetAvailableTimeSlot objectGetAvailableTimeSlot = new ObjectGetAvailableTimeSlot();
    ObjectSetProfileImage objectSetProfileImage = new ObjectSetProfileImage();
    ObjectGetProfileDetails objectGetProfileDetails = new ObjectGetProfileDetails();
    ObjectUpdateProfileDetails objectUpdateProfileDetails = new ObjectUpdateProfileDetails();
    ObjectUpdateProfileEducation objectUpdateProfileEducation = new ObjectUpdateProfileEducation();
    ObjectSendNewEnquiry objectSendNewEnquiry = new ObjectSendNewEnquiry();
    ObjectDeleteProfileEducationDetails objectDeleteProfileEducationDetails = new ObjectDeleteProfileEducationDetails();
    ObjectViewProfileDetails objectViewProfileDetails = new ObjectViewProfileDetails();
    ObjectLoadVASSettings objectLoadVASSettings = new ObjectLoadVASSettings();
    ObjectSaveVASRequirements objectSaveVASRequirements = new ObjectSaveVASRequirements();
    ObjectLoadProfileSettings objectLoadProfileSettings = new ObjectLoadProfileSettings();
    ObjectUpdateGroupJoinRequest objectUpdateGroupJoinRequest = new ObjectUpdateGroupJoinRequest();
    ObjectRemoveGroupMember objectRemoveGroupMember = new ObjectRemoveGroupMember();
    ObjectChangeGroupDetails objectChangeGroupDetails = new ObjectChangeGroupDetails();
    ObjectForgotPassword objectForgotPassword = new ObjectForgotPassword();

    ObjectGetKey objectGetKey = new ObjectGetKey();
    ObjectRemoveOffer objectRemoveOffer = new ObjectRemoveOffer();
}